baseURL = "https://dongxiaba.site"
languageCode = "en-us"
title = "冬夏爸"
theme="ananke"

DefaultContentLanguage = "CN"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
    favicon="/img/icon-32.png"